#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_windows_os_info(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(local_agents_dir + "/plugins/windows_os_info.cmd",
                     plugins_dir + "/windows_os_info.cmd")


bakery_info["windows_os_info"] = {
    "bake_function" : bake_windows_os_info,
    "os"            : [ "windows", ],
}
