#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_ms_logins(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(local_agents_dir + "/plugins/ms_logins.ps1",
                     plugins_dir + "/ms_logins.ps1") 

bakery_info["ms_logins"] = {
    "bake_function" : bake_ms_logins,
    "os"            : [ "windows", ],
}
