#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_mscs_resources(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(local_agents_dir + "/plugins/mscs_resources.ps1",
                     plugins_dir + "/mscs_resources.ps1")


bakery_info["mscs_resources"] = {
    "bake_function" : bake_mscs_resources,
    "os"            : [ "windows", ],
}
