#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_mscs_nodes(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(local_agents_dir + "/plugins/mscs_nodes.ps1",
                     plugins_dir + "/mscs_nodes.ps1")


bakery_info["mscs_nodes"] = {
    "bake_function" : bake_mscs_nodes,
    "os"            : [ "windows", ],
}
