#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_ms_scep(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(local_agents_dir + "/plugins/win_defender.ps1",
                     plugins_dir + "/win_defender.ps1")


bakery_info["win_defender"] = {
    "bake_function" : bake_win_defender,
    "os"            : [ "windows", ],
}
